# https://docs.sourcery.ai/Configuration/Project-Settings/

version: "1"

ignore:
  - ~/.pyenv
  - ~/.rye
  - ~/.vscode
  - ~/.cache
  - ~/.config
  - ~/.local
  - .bzr"
  - .direnv"
  - .eggs"
  - .git"
  - .git-rewrite"
  - .github"
  - .hg"
  - .ipynb_checkpoints"
  - .mypy_cache"
  - .nox"
  - .pants.d"
  - .pyenv"
  - .pytest_cache"
  - .pytype"
  - .ruff_cache"
  - .svn"
  - .tox"
  - .venv"
  - .env"
  - .vscode"
  - .DS_Store"
  - .history"
  - __pypackages__"
  - __pycache__"
  - _build"
  - buck-out"
  - build"
  - dist"
  - node_modules"
  - site-packages"
  - venv"
  - env"
  - vendor"
  - .rye"
  - .cache"
  - .config"
  - .local"

rule_settings:
  enable:
    - default
  disable: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.11"

metrics:
  quality_threshold: 25.0

clone_detection:
  min_lines: 1
  min_duplicates: 2
  identical_clones_only: false
