# This is custom config file that defines some project wide things such as the names of packages.
# Primarily used by the CI.
platform_independent_packages:
  - experimentation
  - modular_robot
  # - modular_robot_physical
  - modular_robot_simulation
  - simulation
  - simulators/mujoco_simulator
platform_dependent_packages:
  - ci_group
examples:
  - 000_simulate_single_robot
  - 001_evaluate_single_robot
  - 002_evaluate_multiple_isolated_robots
  - 003_evaluate_multiple_interacting_robots
  - 010_brain_with_feedback
  - 011_custom_brain
  - 012_custom_terrain
  - 020_experiment_setup
  - 021_experiment_setup_aim
  - 030_simple_ea_xor
  - 031_simple_ea_xor_database
  - 040_robot_brain_cmaes
  - 041_robot_brain_cmaes_database
  - 050_robot_bodybrain_ea
  - 051_robot_bodybrain_ea_database
  - 100_physical_robot_remote
  - 101_compare_simulated_and_physical_robot
tests-dir: tests
examples-dir: examples
revolve2-namespace: revolve2
