# This is custom config file that defines some project wide things such as the names of packages.
# Primarily used by the CI.
platform_independent_packages:
  - experimentation
  - modular_robot
  # - modular_robot_physical
  - modular_robot_simulation
  - simulation
  - simulators/mujoco_simulator
platform_dependent_packages:
  - ci_group
examples:
  - 000_simulate_single_robot
  - 001_evaluate_single_robot
  - 002_evaluate_multiple_isolated_robots
  - 003_evaluate_multiple_interacting_robots
  - 004_brain_with_feedback
  - 005_custom_brain
  - 006_custom_terrain
  - 007_experiment_setup
  - 008_simple_ea_xor
  - 009_simple_ea_xor_database
  - 010_robot_brain_cmaes
  - 011_robot_brain_cmaes_database
  - 012_robot_bodybrain_ea
  - 013_robot_bodybrain_ea_database
  - 014_physical_robot_remote
  - 015_compare_simulated_and_physical_robot
tests-dir: tests
examples-dir: examples
revolve2-namespace: revolve2
